baseURL = 'https://easyhugowriter.github.io/'
languageCode = 'en-us'
theme = ["PaperMod"]
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
pygmentsUseClasses = true
title = 'EasyHugo'

[minify]
disableXML = true
minifyOutput = true


[pagination]
pagerSize=10

[params]
env = "production"
description = "ExampleSite description"
keywords = ["Blog", "EasyHugo", "Hugo"]
author = "EasyHugo"
ShowReadingTime = true
ShowShareButtons = true

ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = true
tocopen = true


[params.homeInfoParams]
Title = "Hi there 👋"
Content = "Welcome to my blog"


[[params.socialIcons]]
name = "x"
url = "https://x.com/"

[[params.socialIcons]]
name = "stackoverflow"
url = "https://stackoverflow.com"

[[params.socialIcons]]
name = "github"
url = "https://github.com/"


[params.analytics.google]
SiteVerificationTag = "XYZabc"

[params.analytics.bing]
SiteVerificationTag = "XYZabc"

[params.analytics.yandex]
SiteVerificationTag = "XYZabc"

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 10

[[menu.main]]
identifier = "categories"
name = "categories"
url = "/categories/"
weight = 20

[[menu.main]]
name = "Archive"
url = "archives"
weight = 30

[[menu.main]]
name = "Search"
url = "search/"
weight = 40


[markup.highlight]
noClasses = false


[outputs]
home = ["HTML", "RSS", "JSON"]